package com.altas.erp.eds.entity;

public class AccountChartTemplateEntityWithBLOBs extends AccountChartTemplateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_chart_template.bank_account_code_prefix
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String bankAccountCodePrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_chart_template.cash_account_code_prefix
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String cashAccountCodePrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_chart_template.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_chart_template.bank_account_code_prefix
     *
     * @return the value of account_chart_template.bank_account_code_prefix
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getBankAccountCodePrefix() {
        return bankAccountCodePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_chart_template.bank_account_code_prefix
     *
     * @param bankAccountCodePrefix the value for account_chart_template.bank_account_code_prefix
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setBankAccountCodePrefix(String bankAccountCodePrefix) {
        this.bankAccountCodePrefix = bankAccountCodePrefix == null ? null : bankAccountCodePrefix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_chart_template.cash_account_code_prefix
     *
     * @return the value of account_chart_template.cash_account_code_prefix
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getCashAccountCodePrefix() {
        return cashAccountCodePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_chart_template.cash_account_code_prefix
     *
     * @param cashAccountCodePrefix the value for account_chart_template.cash_account_code_prefix
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCashAccountCodePrefix(String cashAccountCodePrefix) {
        this.cashAccountCodePrefix = cashAccountCodePrefix == null ? null : cashAccountCodePrefix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_chart_template.name
     *
     * @return the value of account_chart_template.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_chart_template.name
     *
     * @param name the value for account_chart_template.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}