package com.altas.erp.eds.entity;

import java.util.Date;

public class AccountReportPartnerLedgerEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_report_partner_ledger.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_report_partner_ledger.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_report_partner_ledger.reconciled
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean reconciled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_report_partner_ledger.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_report_partner_ledger.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_report_partner_ledger.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_report_partner_ledger.date_to
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date dateTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_report_partner_ledger.amount_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean amountCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_report_partner_ledger.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_report_partner_ledger.date_from
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date dateFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_report_partner_ledger.id
     *
     * @return the value of account_report_partner_ledger.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_report_partner_ledger.id
     *
     * @param id the value for account_report_partner_ledger.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_report_partner_ledger.create_uid
     *
     * @return the value of account_report_partner_ledger.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_report_partner_ledger.create_uid
     *
     * @param createUid the value for account_report_partner_ledger.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_report_partner_ledger.reconciled
     *
     * @return the value of account_report_partner_ledger.reconciled
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getReconciled() {
        return reconciled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_report_partner_ledger.reconciled
     *
     * @param reconciled the value for account_report_partner_ledger.reconciled
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setReconciled(Boolean reconciled) {
        this.reconciled = reconciled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_report_partner_ledger.company_id
     *
     * @return the value of account_report_partner_ledger.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_report_partner_ledger.company_id
     *
     * @param companyId the value for account_report_partner_ledger.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_report_partner_ledger.create_date
     *
     * @return the value of account_report_partner_ledger.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_report_partner_ledger.create_date
     *
     * @param createDate the value for account_report_partner_ledger.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_report_partner_ledger.write_date
     *
     * @return the value of account_report_partner_ledger.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_report_partner_ledger.write_date
     *
     * @param writeDate the value for account_report_partner_ledger.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_report_partner_ledger.date_to
     *
     * @return the value of account_report_partner_ledger.date_to
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getDateTo() {
        return dateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_report_partner_ledger.date_to
     *
     * @param dateTo the value for account_report_partner_ledger.date_to
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_report_partner_ledger.amount_currency
     *
     * @return the value of account_report_partner_ledger.amount_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getAmountCurrency() {
        return amountCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_report_partner_ledger.amount_currency
     *
     * @param amountCurrency the value for account_report_partner_ledger.amount_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAmountCurrency(Boolean amountCurrency) {
        this.amountCurrency = amountCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_report_partner_ledger.write_uid
     *
     * @return the value of account_report_partner_ledger.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_report_partner_ledger.write_uid
     *
     * @param writeUid the value for account_report_partner_ledger.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_report_partner_ledger.date_from
     *
     * @return the value of account_report_partner_ledger.date_from
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getDateFrom() {
        return dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_report_partner_ledger.date_from
     *
     * @param dateFrom the value for account_report_partner_ledger.date_from
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }
}