package com.altas.erp.eds.entity;

import java.util.Date;

public class AccountPartialReconcileEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer currencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.credit_move_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer creditMoveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.full_reconcile_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer fullReconcileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.amount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.debit_move_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer debitMoveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.amount_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double amountCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_partial_reconcile.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.id
     *
     * @return the value of account_partial_reconcile.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.id
     *
     * @param id the value for account_partial_reconcile.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.create_uid
     *
     * @return the value of account_partial_reconcile.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.create_uid
     *
     * @param createUid the value for account_partial_reconcile.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.currency_id
     *
     * @return the value of account_partial_reconcile.currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCurrencyId() {
        return currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.currency_id
     *
     * @param currencyId the value for account_partial_reconcile.currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.credit_move_id
     *
     * @return the value of account_partial_reconcile.credit_move_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreditMoveId() {
        return creditMoveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.credit_move_id
     *
     * @param creditMoveId the value for account_partial_reconcile.credit_move_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreditMoveId(Integer creditMoveId) {
        this.creditMoveId = creditMoveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.full_reconcile_id
     *
     * @return the value of account_partial_reconcile.full_reconcile_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getFullReconcileId() {
        return fullReconcileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.full_reconcile_id
     *
     * @param fullReconcileId the value for account_partial_reconcile.full_reconcile_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setFullReconcileId(Integer fullReconcileId) {
        this.fullReconcileId = fullReconcileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.company_id
     *
     * @return the value of account_partial_reconcile.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.company_id
     *
     * @param companyId the value for account_partial_reconcile.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.write_uid
     *
     * @return the value of account_partial_reconcile.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.write_uid
     *
     * @param writeUid the value for account_partial_reconcile.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.amount
     *
     * @return the value of account_partial_reconcile.amount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.amount
     *
     * @param amount the value for account_partial_reconcile.amount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.debit_move_id
     *
     * @return the value of account_partial_reconcile.debit_move_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getDebitMoveId() {
        return debitMoveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.debit_move_id
     *
     * @param debitMoveId the value for account_partial_reconcile.debit_move_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDebitMoveId(Integer debitMoveId) {
        this.debitMoveId = debitMoveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.write_date
     *
     * @return the value of account_partial_reconcile.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.write_date
     *
     * @param writeDate the value for account_partial_reconcile.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.amount_currency
     *
     * @return the value of account_partial_reconcile.amount_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getAmountCurrency() {
        return amountCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.amount_currency
     *
     * @param amountCurrency the value for account_partial_reconcile.amount_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAmountCurrency(Double amountCurrency) {
        this.amountCurrency = amountCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_partial_reconcile.create_date
     *
     * @return the value of account_partial_reconcile.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_partial_reconcile.create_date
     *
     * @param createDate the value for account_partial_reconcile.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}