package com.altas.erp.eds.entity;

public class AccountFiscalPositionResCountryStateRelEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_fiscal_position_res_country_state_rel.account_fiscal_position_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer accountFiscalPositionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_fiscal_position_res_country_state_rel.res_country_state_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer resCountryStateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_fiscal_position_res_country_state_rel.account_fiscal_position_id
     *
     * @return the value of account_fiscal_position_res_country_state_rel.account_fiscal_position_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getAccountFiscalPositionId() {
        return accountFiscalPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_fiscal_position_res_country_state_rel.account_fiscal_position_id
     *
     * @param accountFiscalPositionId the value for account_fiscal_position_res_country_state_rel.account_fiscal_position_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAccountFiscalPositionId(Integer accountFiscalPositionId) {
        this.accountFiscalPositionId = accountFiscalPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_fiscal_position_res_country_state_rel.res_country_state_id
     *
     * @return the value of account_fiscal_position_res_country_state_rel.res_country_state_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getResCountryStateId() {
        return resCountryStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_fiscal_position_res_country_state_rel.res_country_state_id
     *
     * @param resCountryStateId the value for account_fiscal_position_res_country_state_rel.res_country_state_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setResCountryStateId(Integer resCountryStateId) {
        this.resCountryStateId = resCountryStateId;
    }
}