package com.altas.erp.eds.entity;

public class AccountInvoiceRefundEntityWithBLOBs extends AccountInvoiceRefundEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_invoice_refund.filter_refund
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String filterRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_invoice_refund.description
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_invoice_refund.filter_refund
     *
     * @return the value of account_invoice_refund.filter_refund
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getFilterRefund() {
        return filterRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_invoice_refund.filter_refund
     *
     * @param filterRefund the value for account_invoice_refund.filter_refund
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setFilterRefund(String filterRefund) {
        this.filterRefund = filterRefund == null ? null : filterRefund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_invoice_refund.description
     *
     * @return the value of account_invoice_refund.description
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_invoice_refund.description
     *
     * @param description the value for account_invoice_refund.description
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}