package com.altas.erp.eds.entity;

public class AccountAnalyticLineTagRelEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_analytic_line_tag_rel.line_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer lineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_analytic_line_tag_rel.tag_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_analytic_line_tag_rel.line_id
     *
     * @return the value of account_analytic_line_tag_rel.line_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_analytic_line_tag_rel.line_id
     *
     * @param lineId the value for account_analytic_line_tag_rel.line_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setLineId(Integer lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_analytic_line_tag_rel.tag_id
     *
     * @return the value of account_analytic_line_tag_rel.tag_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_analytic_line_tag_rel.tag_id
     *
     * @param tagId the value for account_analytic_line_tag_rel.tag_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }
}