package com.altas.erp.eds.entity;

public class AccountJournalAccountPrintJournalRelEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_journal_account_print_journal_rel.account_print_journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer accountPrintJournalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_journal_account_print_journal_rel.account_journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer accountJournalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_journal_account_print_journal_rel.account_print_journal_id
     *
     * @return the value of account_journal_account_print_journal_rel.account_print_journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getAccountPrintJournalId() {
        return accountPrintJournalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_journal_account_print_journal_rel.account_print_journal_id
     *
     * @param accountPrintJournalId the value for account_journal_account_print_journal_rel.account_print_journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAccountPrintJournalId(Integer accountPrintJournalId) {
        this.accountPrintJournalId = accountPrintJournalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_journal_account_print_journal_rel.account_journal_id
     *
     * @return the value of account_journal_account_print_journal_rel.account_journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getAccountJournalId() {
        return accountJournalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_journal_account_print_journal_rel.account_journal_id
     *
     * @param accountJournalId the value for account_journal_account_print_journal_rel.account_journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAccountJournalId(Integer accountJournalId) {
        this.accountJournalId = accountJournalId;
    }
}