package com.altas.erp.eds.entity;

import java.util.Date;

public class AccountFinancialReportEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial_report.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial_report.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial_report.level
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial_report.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial_report.style_overwrite
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer styleOverwrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial_report.sign
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial_report.parent_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial_report.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial_report.account_report_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer accountReportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial_report.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial_report.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial_report.id
     *
     * @return the value of account_financial_report.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial_report.id
     *
     * @param id the value for account_financial_report.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial_report.create_uid
     *
     * @return the value of account_financial_report.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial_report.create_uid
     *
     * @param createUid the value for account_financial_report.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial_report.level
     *
     * @return the value of account_financial_report.level
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial_report.level
     *
     * @param level the value for account_financial_report.level
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial_report.sequence
     *
     * @return the value of account_financial_report.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial_report.sequence
     *
     * @param sequence the value for account_financial_report.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial_report.style_overwrite
     *
     * @return the value of account_financial_report.style_overwrite
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getStyleOverwrite() {
        return styleOverwrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial_report.style_overwrite
     *
     * @param styleOverwrite the value for account_financial_report.style_overwrite
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setStyleOverwrite(Integer styleOverwrite) {
        this.styleOverwrite = styleOverwrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial_report.sign
     *
     * @return the value of account_financial_report.sign
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial_report.sign
     *
     * @param sign the value for account_financial_report.sign
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSign(Integer sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial_report.parent_id
     *
     * @return the value of account_financial_report.parent_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial_report.parent_id
     *
     * @param parentId the value for account_financial_report.parent_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial_report.write_date
     *
     * @return the value of account_financial_report.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial_report.write_date
     *
     * @param writeDate the value for account_financial_report.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial_report.account_report_id
     *
     * @return the value of account_financial_report.account_report_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getAccountReportId() {
        return accountReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial_report.account_report_id
     *
     * @param accountReportId the value for account_financial_report.account_report_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAccountReportId(Integer accountReportId) {
        this.accountReportId = accountReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial_report.create_date
     *
     * @return the value of account_financial_report.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial_report.create_date
     *
     * @param createDate the value for account_financial_report.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial_report.write_uid
     *
     * @return the value of account_financial_report.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial_report.write_uid
     *
     * @param writeUid the value for account_financial_report.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }
}