package com.altas.erp.eds.entity;

public class AccountAnalyticTagAccountInvoiceLineRelEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_analytic_tag_account_invoice_line_rel.account_invoice_line_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer accountInvoiceLineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_analytic_tag_account_invoice_line_rel.account_analytic_tag_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer accountAnalyticTagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_analytic_tag_account_invoice_line_rel.account_invoice_line_id
     *
     * @return the value of account_analytic_tag_account_invoice_line_rel.account_invoice_line_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getAccountInvoiceLineId() {
        return accountInvoiceLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_analytic_tag_account_invoice_line_rel.account_invoice_line_id
     *
     * @param accountInvoiceLineId the value for account_analytic_tag_account_invoice_line_rel.account_invoice_line_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAccountInvoiceLineId(Integer accountInvoiceLineId) {
        this.accountInvoiceLineId = accountInvoiceLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_analytic_tag_account_invoice_line_rel.account_analytic_tag_id
     *
     * @return the value of account_analytic_tag_account_invoice_line_rel.account_analytic_tag_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getAccountAnalyticTagId() {
        return accountAnalyticTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_analytic_tag_account_invoice_line_rel.account_analytic_tag_id
     *
     * @param accountAnalyticTagId the value for account_analytic_tag_account_invoice_line_rel.account_analytic_tag_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAccountAnalyticTagId(Integer accountAnalyticTagId) {
        this.accountAnalyticTagId = accountAnalyticTagId;
    }
}