package com.altas.erp.eds.entity;

public class AccountAccountTemplateAccountTagEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_account_template_account_tag.account_account_template_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer accountAccountTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_account_template_account_tag.account_account_tag_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer accountAccountTagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_account_template_account_tag.account_account_template_id
     *
     * @return the value of account_account_template_account_tag.account_account_template_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getAccountAccountTemplateId() {
        return accountAccountTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_account_template_account_tag.account_account_template_id
     *
     * @param accountAccountTemplateId the value for account_account_template_account_tag.account_account_template_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAccountAccountTemplateId(Integer accountAccountTemplateId) {
        this.accountAccountTemplateId = accountAccountTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_account_template_account_tag.account_account_tag_id
     *
     * @return the value of account_account_template_account_tag.account_account_tag_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getAccountAccountTagId() {
        return accountAccountTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_account_template_account_tag.account_account_tag_id
     *
     * @param accountAccountTagId the value for account_account_template_account_tag.account_account_tag_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAccountAccountTagId(Integer accountAccountTagId) {
        this.accountAccountTagId = accountAccountTagId;
    }
}