package com.altas.erp.eds.entity;

import java.util.Date;

public class AccountTaxEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.include_base_amount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean includeBaseAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.analytic
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean analytic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.tax_adjustment
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean taxAdjustment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.refund_account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer refundAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.tax_group_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer taxGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.amount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_tax.price_include
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean priceInclude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.id
     *
     * @return the value of account_tax.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.id
     *
     * @param id the value for account_tax.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.create_date
     *
     * @return the value of account_tax.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.create_date
     *
     * @param createDate the value for account_tax.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.sequence
     *
     * @return the value of account_tax.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.sequence
     *
     * @param sequence the value for account_tax.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.write_uid
     *
     * @return the value of account_tax.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.write_uid
     *
     * @param writeUid the value for account_tax.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.include_base_amount
     *
     * @return the value of account_tax.include_base_amount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getIncludeBaseAmount() {
        return includeBaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.include_base_amount
     *
     * @param includeBaseAmount the value for account_tax.include_base_amount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setIncludeBaseAmount(Boolean includeBaseAmount) {
        this.includeBaseAmount = includeBaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.create_uid
     *
     * @return the value of account_tax.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.create_uid
     *
     * @param createUid the value for account_tax.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.company_id
     *
     * @return the value of account_tax.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.company_id
     *
     * @param companyId the value for account_tax.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.analytic
     *
     * @return the value of account_tax.analytic
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getAnalytic() {
        return analytic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.analytic
     *
     * @param analytic the value for account_tax.analytic
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAnalytic(Boolean analytic) {
        this.analytic = analytic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.account_id
     *
     * @return the value of account_tax.account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.account_id
     *
     * @param accountId the value for account_tax.account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.tax_adjustment
     *
     * @return the value of account_tax.tax_adjustment
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getTaxAdjustment() {
        return taxAdjustment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.tax_adjustment
     *
     * @param taxAdjustment the value for account_tax.tax_adjustment
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setTaxAdjustment(Boolean taxAdjustment) {
        this.taxAdjustment = taxAdjustment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.refund_account_id
     *
     * @return the value of account_tax.refund_account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getRefundAccountId() {
        return refundAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.refund_account_id
     *
     * @param refundAccountId the value for account_tax.refund_account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setRefundAccountId(Integer refundAccountId) {
        this.refundAccountId = refundAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.write_date
     *
     * @return the value of account_tax.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.write_date
     *
     * @param writeDate the value for account_tax.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.active
     *
     * @return the value of account_tax.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.active
     *
     * @param active the value for account_tax.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.tax_group_id
     *
     * @return the value of account_tax.tax_group_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getTaxGroupId() {
        return taxGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.tax_group_id
     *
     * @param taxGroupId the value for account_tax.tax_group_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setTaxGroupId(Integer taxGroupId) {
        this.taxGroupId = taxGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.amount
     *
     * @return the value of account_tax.amount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.amount
     *
     * @param amount the value for account_tax.amount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_tax.price_include
     *
     * @return the value of account_tax.price_include
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getPriceInclude() {
        return priceInclude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_tax.price_include
     *
     * @param priceInclude the value for account_tax.price_include
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPriceInclude(Boolean priceInclude) {
        this.priceInclude = priceInclude;
    }
}