package com.altas.erp.eds.entity;

public class AccountReconcileModelTemplateEntityWithBLOBs extends AccountReconcileModelTemplateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_reconcile_model_template.amount_type
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String amountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_reconcile_model_template.second_amount_type
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String secondAmountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_reconcile_model_template.label
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_reconcile_model_template.second_label
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String secondLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_reconcile_model_template.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_reconcile_model_template.amount_type
     *
     * @return the value of account_reconcile_model_template.amount_type
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getAmountType() {
        return amountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_reconcile_model_template.amount_type
     *
     * @param amountType the value for account_reconcile_model_template.amount_type
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAmountType(String amountType) {
        this.amountType = amountType == null ? null : amountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_reconcile_model_template.second_amount_type
     *
     * @return the value of account_reconcile_model_template.second_amount_type
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getSecondAmountType() {
        return secondAmountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_reconcile_model_template.second_amount_type
     *
     * @param secondAmountType the value for account_reconcile_model_template.second_amount_type
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSecondAmountType(String secondAmountType) {
        this.secondAmountType = secondAmountType == null ? null : secondAmountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_reconcile_model_template.label
     *
     * @return the value of account_reconcile_model_template.label
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_reconcile_model_template.label
     *
     * @param label the value for account_reconcile_model_template.label
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_reconcile_model_template.second_label
     *
     * @return the value of account_reconcile_model_template.second_label
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getSecondLabel() {
        return secondLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_reconcile_model_template.second_label
     *
     * @param secondLabel the value for account_reconcile_model_template.second_label
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSecondLabel(String secondLabel) {
        this.secondLabel = secondLabel == null ? null : secondLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_reconcile_model_template.name
     *
     * @return the value of account_reconcile_model_template.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_reconcile_model_template.name
     *
     * @param name the value for account_reconcile_model_template.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}