package com.altas.erp.eds.entity;

import java.util.Date;

public class AccountMoveLineEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.statement_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer statementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer journalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer currencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.date_maturity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date dateMaturity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.user_type_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer userTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.partner_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer partnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.blocked
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean blocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.analytic_account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer analyticAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.full_reconcile_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer fullReconcileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.amount_residual
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double amountResidual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.credit_cash_basis
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double creditCashBasis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.amount_residual_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double amountResidualCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.debit
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double debit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.debit_cash_basis
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double debitCashBasis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.reconciled
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean reconciled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.tax_exigible
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean taxExigible;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.balance_cash_basis
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double balanceCashBasis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.move_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer moveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.product_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.payment_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.company_currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer companyCurrencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.invoice_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer invoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.tax_line_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer taxLineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.credit
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.product_uom_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer productUomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.amount_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double amountCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.balance
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_move_line.quantity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.id
     *
     * @return the value of account_move_line.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.id
     *
     * @param id the value for account_move_line.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.create_date
     *
     * @return the value of account_move_line.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.create_date
     *
     * @param createDate the value for account_move_line.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.statement_id
     *
     * @return the value of account_move_line.statement_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getStatementId() {
        return statementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.statement_id
     *
     * @param statementId the value for account_move_line.statement_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setStatementId(Integer statementId) {
        this.statementId = statementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.journal_id
     *
     * @return the value of account_move_line.journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getJournalId() {
        return journalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.journal_id
     *
     * @param journalId the value for account_move_line.journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setJournalId(Integer journalId) {
        this.journalId = journalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.currency_id
     *
     * @return the value of account_move_line.currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCurrencyId() {
        return currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.currency_id
     *
     * @param currencyId the value for account_move_line.currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.date_maturity
     *
     * @return the value of account_move_line.date_maturity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getDateMaturity() {
        return dateMaturity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.date_maturity
     *
     * @param dateMaturity the value for account_move_line.date_maturity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDateMaturity(Date dateMaturity) {
        this.dateMaturity = dateMaturity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.user_type_id
     *
     * @return the value of account_move_line.user_type_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getUserTypeId() {
        return userTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.user_type_id
     *
     * @param userTypeId the value for account_move_line.user_type_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setUserTypeId(Integer userTypeId) {
        this.userTypeId = userTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.partner_id
     *
     * @return the value of account_move_line.partner_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.partner_id
     *
     * @param partnerId the value for account_move_line.partner_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPartnerId(Integer partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.blocked
     *
     * @return the value of account_move_line.blocked
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getBlocked() {
        return blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.blocked
     *
     * @param blocked the value for account_move_line.blocked
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.analytic_account_id
     *
     * @return the value of account_move_line.analytic_account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getAnalyticAccountId() {
        return analyticAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.analytic_account_id
     *
     * @param analyticAccountId the value for account_move_line.analytic_account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAnalyticAccountId(Integer analyticAccountId) {
        this.analyticAccountId = analyticAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.create_uid
     *
     * @return the value of account_move_line.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.create_uid
     *
     * @param createUid the value for account_move_line.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.full_reconcile_id
     *
     * @return the value of account_move_line.full_reconcile_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getFullReconcileId() {
        return fullReconcileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.full_reconcile_id
     *
     * @param fullReconcileId the value for account_move_line.full_reconcile_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setFullReconcileId(Integer fullReconcileId) {
        this.fullReconcileId = fullReconcileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.amount_residual
     *
     * @return the value of account_move_line.amount_residual
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getAmountResidual() {
        return amountResidual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.amount_residual
     *
     * @param amountResidual the value for account_move_line.amount_residual
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAmountResidual(Double amountResidual) {
        this.amountResidual = amountResidual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.company_id
     *
     * @return the value of account_move_line.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.company_id
     *
     * @param companyId the value for account_move_line.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.credit_cash_basis
     *
     * @return the value of account_move_line.credit_cash_basis
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getCreditCashBasis() {
        return creditCashBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.credit_cash_basis
     *
     * @param creditCashBasis the value for account_move_line.credit_cash_basis
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreditCashBasis(Double creditCashBasis) {
        this.creditCashBasis = creditCashBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.amount_residual_currency
     *
     * @return the value of account_move_line.amount_residual_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getAmountResidualCurrency() {
        return amountResidualCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.amount_residual_currency
     *
     * @param amountResidualCurrency the value for account_move_line.amount_residual_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAmountResidualCurrency(Double amountResidualCurrency) {
        this.amountResidualCurrency = amountResidualCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.debit
     *
     * @return the value of account_move_line.debit
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getDebit() {
        return debit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.debit
     *
     * @param debit the value for account_move_line.debit
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDebit(Double debit) {
        this.debit = debit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.account_id
     *
     * @return the value of account_move_line.account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.account_id
     *
     * @param accountId the value for account_move_line.account_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.debit_cash_basis
     *
     * @return the value of account_move_line.debit_cash_basis
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getDebitCashBasis() {
        return debitCashBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.debit_cash_basis
     *
     * @param debitCashBasis the value for account_move_line.debit_cash_basis
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDebitCashBasis(Double debitCashBasis) {
        this.debitCashBasis = debitCashBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.reconciled
     *
     * @return the value of account_move_line.reconciled
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getReconciled() {
        return reconciled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.reconciled
     *
     * @param reconciled the value for account_move_line.reconciled
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setReconciled(Boolean reconciled) {
        this.reconciled = reconciled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.tax_exigible
     *
     * @return the value of account_move_line.tax_exigible
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getTaxExigible() {
        return taxExigible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.tax_exigible
     *
     * @param taxExigible the value for account_move_line.tax_exigible
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setTaxExigible(Boolean taxExigible) {
        this.taxExigible = taxExigible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.balance_cash_basis
     *
     * @return the value of account_move_line.balance_cash_basis
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getBalanceCashBasis() {
        return balanceCashBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.balance_cash_basis
     *
     * @param balanceCashBasis the value for account_move_line.balance_cash_basis
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setBalanceCashBasis(Double balanceCashBasis) {
        this.balanceCashBasis = balanceCashBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.write_date
     *
     * @return the value of account_move_line.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.write_date
     *
     * @param writeDate the value for account_move_line.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.date
     *
     * @return the value of account_move_line.date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.date
     *
     * @param date the value for account_move_line.date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.write_uid
     *
     * @return the value of account_move_line.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.write_uid
     *
     * @param writeUid the value for account_move_line.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.move_id
     *
     * @return the value of account_move_line.move_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getMoveId() {
        return moveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.move_id
     *
     * @param moveId the value for account_move_line.move_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setMoveId(Integer moveId) {
        this.moveId = moveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.product_id
     *
     * @return the value of account_move_line.product_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.product_id
     *
     * @param productId the value for account_move_line.product_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.payment_id
     *
     * @return the value of account_move_line.payment_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.payment_id
     *
     * @param paymentId the value for account_move_line.payment_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.company_currency_id
     *
     * @return the value of account_move_line.company_currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCompanyCurrencyId() {
        return companyCurrencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.company_currency_id
     *
     * @param companyCurrencyId the value for account_move_line.company_currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCompanyCurrencyId(Integer companyCurrencyId) {
        this.companyCurrencyId = companyCurrencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.invoice_id
     *
     * @return the value of account_move_line.invoice_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.invoice_id
     *
     * @param invoiceId the value for account_move_line.invoice_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.tax_line_id
     *
     * @return the value of account_move_line.tax_line_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getTaxLineId() {
        return taxLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.tax_line_id
     *
     * @param taxLineId the value for account_move_line.tax_line_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setTaxLineId(Integer taxLineId) {
        this.taxLineId = taxLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.credit
     *
     * @return the value of account_move_line.credit
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.credit
     *
     * @param credit the value for account_move_line.credit
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCredit(Double credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.product_uom_id
     *
     * @return the value of account_move_line.product_uom_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getProductUomId() {
        return productUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.product_uom_id
     *
     * @param productUomId the value for account_move_line.product_uom_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setProductUomId(Integer productUomId) {
        this.productUomId = productUomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.amount_currency
     *
     * @return the value of account_move_line.amount_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getAmountCurrency() {
        return amountCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.amount_currency
     *
     * @param amountCurrency the value for account_move_line.amount_currency
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAmountCurrency(Double amountCurrency) {
        this.amountCurrency = amountCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.balance
     *
     * @return the value of account_move_line.balance
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.balance
     *
     * @param balance the value for account_move_line.balance
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_move_line.quantity
     *
     * @return the value of account_move_line.quantity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_move_line.quantity
     *
     * @param quantity the value for account_move_line.quantity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
}