package com.altas.erp.eds.entity;

import java.util.Date;

public class BaseImportTestsModelsCharReadonlyEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_import_tests_models_char_readonly.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_import_tests_models_char_readonly.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_import_tests_models_char_readonly.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_import_tests_models_char_readonly.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_import_tests_models_char_readonly.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_import_tests_models_char_readonly.value
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_import_tests_models_char_readonly.id
     *
     * @return the value of base_import_tests_models_char_readonly.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_import_tests_models_char_readonly.id
     *
     * @param id the value for base_import_tests_models_char_readonly.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_import_tests_models_char_readonly.create_uid
     *
     * @return the value of base_import_tests_models_char_readonly.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_import_tests_models_char_readonly.create_uid
     *
     * @param createUid the value for base_import_tests_models_char_readonly.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_import_tests_models_char_readonly.create_date
     *
     * @return the value of base_import_tests_models_char_readonly.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_import_tests_models_char_readonly.create_date
     *
     * @param createDate the value for base_import_tests_models_char_readonly.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_import_tests_models_char_readonly.write_uid
     *
     * @return the value of base_import_tests_models_char_readonly.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_import_tests_models_char_readonly.write_uid
     *
     * @param writeUid the value for base_import_tests_models_char_readonly.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_import_tests_models_char_readonly.write_date
     *
     * @return the value of base_import_tests_models_char_readonly.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_import_tests_models_char_readonly.write_date
     *
     * @param writeDate the value for base_import_tests_models_char_readonly.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_import_tests_models_char_readonly.value
     *
     * @return the value of base_import_tests_models_char_readonly.value
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_import_tests_models_char_readonly.value
     *
     * @param value the value for base_import_tests_models_char_readonly.value
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}