package com.altas.erp.eds.entity;

import java.util.Date;

public class BusPresenceEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_presence.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_presence.user_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_presence.last_presence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date lastPresence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_presence.last_poll
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date lastPoll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_presence.status
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_presence.id
     *
     * @return the value of bus_presence.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_presence.id
     *
     * @param id the value for bus_presence.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_presence.user_id
     *
     * @return the value of bus_presence.user_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_presence.user_id
     *
     * @param userId the value for bus_presence.user_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_presence.last_presence
     *
     * @return the value of bus_presence.last_presence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getLastPresence() {
        return lastPresence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_presence.last_presence
     *
     * @param lastPresence the value for bus_presence.last_presence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setLastPresence(Date lastPresence) {
        this.lastPresence = lastPresence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_presence.last_poll
     *
     * @return the value of bus_presence.last_poll
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getLastPoll() {
        return lastPoll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_presence.last_poll
     *
     * @param lastPoll the value for bus_presence.last_poll
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setLastPoll(Date lastPoll) {
        this.lastPoll = lastPoll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_presence.status
     *
     * @return the value of bus_presence.status
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_presence.status
     *
     * @param status the value for bus_presence.status
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}