package com.altas.erp.eds.entity;

public class ChangePasswordUserEntityWithBLOBs extends ChangePasswordUserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_password_user.user_login
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String userLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_password_user.new_passwd
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String newPasswd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_password_user.user_login
     *
     * @return the value of change_password_user.user_login
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getUserLogin() {
        return userLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_password_user.user_login
     *
     * @param userLogin the value for change_password_user.user_login
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin == null ? null : userLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_password_user.new_passwd
     *
     * @return the value of change_password_user.new_passwd
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getNewPasswd() {
        return newPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_password_user.new_passwd
     *
     * @param newPasswd the value for change_password_user.new_passwd
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setNewPasswd(String newPasswd) {
        this.newPasswd = newPasswd == null ? null : newPasswd.trim();
    }
}