package com.altas.erp.eds.entity;

import java.util.Date;

public class CrmTeamEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.color
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.user_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.message_last_post
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date messageLastPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.use_quotations
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean useQuotations;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.invoiced_target
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer invoicedTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_team.use_invoices
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean useInvoices;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.id
     *
     * @return the value of crm_team.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.id
     *
     * @param id the value for crm_team.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.create_date
     *
     * @return the value of crm_team.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.create_date
     *
     * @param createDate the value for crm_team.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.color
     *
     * @return the value of crm_team.color
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.color
     *
     * @param color the value for crm_team.color
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setColor(Integer color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.write_uid
     *
     * @return the value of crm_team.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.write_uid
     *
     * @param writeUid the value for crm_team.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.create_uid
     *
     * @return the value of crm_team.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.create_uid
     *
     * @param createUid the value for crm_team.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.user_id
     *
     * @return the value of crm_team.user_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.user_id
     *
     * @param userId the value for crm_team.user_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.message_last_post
     *
     * @return the value of crm_team.message_last_post
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getMessageLastPost() {
        return messageLastPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.message_last_post
     *
     * @param messageLastPost the value for crm_team.message_last_post
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setMessageLastPost(Date messageLastPost) {
        this.messageLastPost = messageLastPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.company_id
     *
     * @return the value of crm_team.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.company_id
     *
     * @param companyId the value for crm_team.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.write_date
     *
     * @return the value of crm_team.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.write_date
     *
     * @param writeDate the value for crm_team.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.active
     *
     * @return the value of crm_team.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.active
     *
     * @param active the value for crm_team.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.use_quotations
     *
     * @return the value of crm_team.use_quotations
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getUseQuotations() {
        return useQuotations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.use_quotations
     *
     * @param useQuotations the value for crm_team.use_quotations
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setUseQuotations(Boolean useQuotations) {
        this.useQuotations = useQuotations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.invoiced_target
     *
     * @return the value of crm_team.invoiced_target
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getInvoicedTarget() {
        return invoicedTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.invoiced_target
     *
     * @param invoicedTarget the value for crm_team.invoiced_target
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setInvoicedTarget(Integer invoicedTarget) {
        this.invoicedTarget = invoicedTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_team.use_invoices
     *
     * @return the value of crm_team.use_invoices
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getUseInvoices() {
        return useInvoices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_team.use_invoices
     *
     * @param useInvoices the value for crm_team.use_invoices
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setUseInvoices(Boolean useInvoices) {
        this.useInvoices = useInvoices;
    }
}