package com.altas.erp.eds.entity;

import java.util.Date;

public class FetchmailServerEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.object_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.port
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.priority
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.attach
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean attach;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.action_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer actionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.is_ssl
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean isSsl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fetchmail_server.original
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean original;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.id
     *
     * @return the value of fetchmail_server.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.id
     *
     * @param id the value for fetchmail_server.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.create_date
     *
     * @return the value of fetchmail_server.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.create_date
     *
     * @param createDate the value for fetchmail_server.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.write_uid
     *
     * @return the value of fetchmail_server.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.write_uid
     *
     * @param writeUid the value for fetchmail_server.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.active
     *
     * @return the value of fetchmail_server.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.active
     *
     * @param active the value for fetchmail_server.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.create_uid
     *
     * @return the value of fetchmail_server.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.create_uid
     *
     * @param createUid the value for fetchmail_server.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.object_id
     *
     * @return the value of fetchmail_server.object_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.object_id
     *
     * @param objectId the value for fetchmail_server.object_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.port
     *
     * @return the value of fetchmail_server.port
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.port
     *
     * @param port the value for fetchmail_server.port
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.priority
     *
     * @return the value of fetchmail_server.priority
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.priority
     *
     * @param priority the value for fetchmail_server.priority
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.attach
     *
     * @return the value of fetchmail_server.attach
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.attach
     *
     * @param attach the value for fetchmail_server.attach
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAttach(Boolean attach) {
        this.attach = attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.action_id
     *
     * @return the value of fetchmail_server.action_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.action_id
     *
     * @param actionId the value for fetchmail_server.action_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.write_date
     *
     * @return the value of fetchmail_server.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.write_date
     *
     * @param writeDate the value for fetchmail_server.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.date
     *
     * @return the value of fetchmail_server.date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.date
     *
     * @param date the value for fetchmail_server.date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.is_ssl
     *
     * @return the value of fetchmail_server.is_ssl
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getIsSsl() {
        return isSsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.is_ssl
     *
     * @param isSsl the value for fetchmail_server.is_ssl
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setIsSsl(Boolean isSsl) {
        this.isSsl = isSsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fetchmail_server.original
     *
     * @return the value of fetchmail_server.original
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getOriginal() {
        return original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fetchmail_server.original
     *
     * @param original the value for fetchmail_server.original
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setOriginal(Boolean original) {
        this.original = original;
    }
}