package com.altas.erp.eds.entity;

import java.util.Date;

public class IrActWindowViewEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_window_view.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_window_view.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_window_view.multi
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean multi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_window_view.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_window_view.view_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer viewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_window_view.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_window_view.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_window_view.act_window_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer actWindowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_window_view.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_window_view.view_mode
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String viewMode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_window_view.id
     *
     * @return the value of ir_act_window_view.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_window_view.id
     *
     * @param id the value for ir_act_window_view.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_window_view.create_uid
     *
     * @return the value of ir_act_window_view.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_window_view.create_uid
     *
     * @param createUid the value for ir_act_window_view.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_window_view.multi
     *
     * @return the value of ir_act_window_view.multi
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getMulti() {
        return multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_window_view.multi
     *
     * @param multi the value for ir_act_window_view.multi
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setMulti(Boolean multi) {
        this.multi = multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_window_view.sequence
     *
     * @return the value of ir_act_window_view.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_window_view.sequence
     *
     * @param sequence the value for ir_act_window_view.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_window_view.view_id
     *
     * @return the value of ir_act_window_view.view_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getViewId() {
        return viewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_window_view.view_id
     *
     * @param viewId the value for ir_act_window_view.view_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setViewId(Integer viewId) {
        this.viewId = viewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_window_view.write_uid
     *
     * @return the value of ir_act_window_view.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_window_view.write_uid
     *
     * @param writeUid the value for ir_act_window_view.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_window_view.write_date
     *
     * @return the value of ir_act_window_view.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_window_view.write_date
     *
     * @param writeDate the value for ir_act_window_view.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_window_view.act_window_id
     *
     * @return the value of ir_act_window_view.act_window_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getActWindowId() {
        return actWindowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_window_view.act_window_id
     *
     * @param actWindowId the value for ir_act_window_view.act_window_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setActWindowId(Integer actWindowId) {
        this.actWindowId = actWindowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_window_view.create_date
     *
     * @return the value of ir_act_window_view.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_window_view.create_date
     *
     * @param createDate the value for ir_act_window_view.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_window_view.view_mode
     *
     * @return the value of ir_act_window_view.view_mode
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getViewMode() {
        return viewMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_window_view.view_mode
     *
     * @param viewMode the value for ir_act_window_view.view_mode
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setViewMode(String viewMode) {
        this.viewMode = viewMode == null ? null : viewMode.trim();
    }
}