package com.altas.erp.eds.entity;

import java.util.Date;

public class IrActReportXmlEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_report_xml.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_report_xml.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_report_xml.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_report_xml.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_report_xml.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_report_xml.header
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean header;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_report_xml.ir_values_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer irValuesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_report_xml.auto
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean auto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_report_xml.multi
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean multi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_report_xml.attachment_use
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean attachmentUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_act_report_xml.paperformat_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer paperformatId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_report_xml.id
     *
     * @return the value of ir_act_report_xml.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_report_xml.id
     *
     * @param id the value for ir_act_report_xml.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_report_xml.create_uid
     *
     * @return the value of ir_act_report_xml.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_report_xml.create_uid
     *
     * @param createUid the value for ir_act_report_xml.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_report_xml.write_uid
     *
     * @return the value of ir_act_report_xml.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_report_xml.write_uid
     *
     * @param writeUid the value for ir_act_report_xml.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_report_xml.write_date
     *
     * @return the value of ir_act_report_xml.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_report_xml.write_date
     *
     * @param writeDate the value for ir_act_report_xml.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_report_xml.create_date
     *
     * @return the value of ir_act_report_xml.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_report_xml.create_date
     *
     * @param createDate the value for ir_act_report_xml.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_report_xml.header
     *
     * @return the value of ir_act_report_xml.header
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_report_xml.header
     *
     * @param header the value for ir_act_report_xml.header
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setHeader(Boolean header) {
        this.header = header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_report_xml.ir_values_id
     *
     * @return the value of ir_act_report_xml.ir_values_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getIrValuesId() {
        return irValuesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_report_xml.ir_values_id
     *
     * @param irValuesId the value for ir_act_report_xml.ir_values_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setIrValuesId(Integer irValuesId) {
        this.irValuesId = irValuesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_report_xml.auto
     *
     * @return the value of ir_act_report_xml.auto
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getAuto() {
        return auto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_report_xml.auto
     *
     * @param auto the value for ir_act_report_xml.auto
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAuto(Boolean auto) {
        this.auto = auto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_report_xml.multi
     *
     * @return the value of ir_act_report_xml.multi
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getMulti() {
        return multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_report_xml.multi
     *
     * @param multi the value for ir_act_report_xml.multi
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setMulti(Boolean multi) {
        this.multi = multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_report_xml.attachment_use
     *
     * @return the value of ir_act_report_xml.attachment_use
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getAttachmentUse() {
        return attachmentUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_report_xml.attachment_use
     *
     * @param attachmentUse the value for ir_act_report_xml.attachment_use
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAttachmentUse(Boolean attachmentUse) {
        this.attachmentUse = attachmentUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_act_report_xml.paperformat_id
     *
     * @return the value of ir_act_report_xml.paperformat_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getPaperformatId() {
        return paperformatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_act_report_xml.paperformat_id
     *
     * @param paperformatId the value for ir_act_report_xml.paperformat_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPaperformatId(Integer paperformatId) {
        this.paperformatId = paperformatId;
    }
}