package com.altas.erp.eds.entity;

import java.util.Date;

public class IrMailServerEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_mail_server.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_mail_server.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_mail_server.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_mail_server.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_mail_server.smtp_port
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer smtpPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_mail_server.smtp_user
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String smtpUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_mail_server.smtp_pass
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String smtpPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_mail_server.smtp_debug
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean smtpDebug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_mail_server.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_mail_server.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_mail_server.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_mail_server.id
     *
     * @return the value of ir_mail_server.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_mail_server.id
     *
     * @param id the value for ir_mail_server.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_mail_server.create_uid
     *
     * @return the value of ir_mail_server.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_mail_server.create_uid
     *
     * @param createUid the value for ir_mail_server.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_mail_server.sequence
     *
     * @return the value of ir_mail_server.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_mail_server.sequence
     *
     * @param sequence the value for ir_mail_server.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_mail_server.write_uid
     *
     * @return the value of ir_mail_server.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_mail_server.write_uid
     *
     * @param writeUid the value for ir_mail_server.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_mail_server.smtp_port
     *
     * @return the value of ir_mail_server.smtp_port
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getSmtpPort() {
        return smtpPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_mail_server.smtp_port
     *
     * @param smtpPort the value for ir_mail_server.smtp_port
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSmtpPort(Integer smtpPort) {
        this.smtpPort = smtpPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_mail_server.smtp_user
     *
     * @return the value of ir_mail_server.smtp_user
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getSmtpUser() {
        return smtpUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_mail_server.smtp_user
     *
     * @param smtpUser the value for ir_mail_server.smtp_user
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSmtpUser(String smtpUser) {
        this.smtpUser = smtpUser == null ? null : smtpUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_mail_server.smtp_pass
     *
     * @return the value of ir_mail_server.smtp_pass
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getSmtpPass() {
        return smtpPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_mail_server.smtp_pass
     *
     * @param smtpPass the value for ir_mail_server.smtp_pass
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSmtpPass(String smtpPass) {
        this.smtpPass = smtpPass == null ? null : smtpPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_mail_server.smtp_debug
     *
     * @return the value of ir_mail_server.smtp_debug
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getSmtpDebug() {
        return smtpDebug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_mail_server.smtp_debug
     *
     * @param smtpDebug the value for ir_mail_server.smtp_debug
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSmtpDebug(Boolean smtpDebug) {
        this.smtpDebug = smtpDebug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_mail_server.write_date
     *
     * @return the value of ir_mail_server.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_mail_server.write_date
     *
     * @param writeDate the value for ir_mail_server.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_mail_server.active
     *
     * @return the value of ir_mail_server.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_mail_server.active
     *
     * @param active the value for ir_mail_server.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_mail_server.create_date
     *
     * @return the value of ir_mail_server.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_mail_server.create_date
     *
     * @param createDate the value for ir_mail_server.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}