package com.altas.erp.eds.entity;

public class IrModelFieldsGroupRelEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_model_fields_group_rel.field_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer fieldId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_model_fields_group_rel.group_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_model_fields_group_rel.field_id
     *
     * @return the value of ir_model_fields_group_rel.field_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_model_fields_group_rel.field_id
     *
     * @param fieldId the value for ir_model_fields_group_rel.field_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setFieldId(Integer fieldId) {
        this.fieldId = fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_model_fields_group_rel.group_id
     *
     * @return the value of ir_model_fields_group_rel.group_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_model_fields_group_rel.group_id
     *
     * @param groupId the value for ir_model_fields_group_rel.group_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}