package com.altas.erp.eds.entity;

public class IrServerObjectLinesEntityWithBLOBs extends IrServerObjectLinesEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_server_object_lines.value
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ir_server_object_lines.type
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_server_object_lines.value
     *
     * @return the value of ir_server_object_lines.value
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_server_object_lines.value
     *
     * @param value the value for ir_server_object_lines.value
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ir_server_object_lines.type
     *
     * @return the value of ir_server_object_lines.type
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ir_server_object_lines.type
     *
     * @param type the value for ir_server_object_lines.type
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}