package com.altas.erp.eds.entity;

public class MailMailResPartnerRelEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_mail_res_partner_rel.mail_mail_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer mailMailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_mail_res_partner_rel.res_partner_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer resPartnerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_mail_res_partner_rel.mail_mail_id
     *
     * @return the value of mail_mail_res_partner_rel.mail_mail_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getMailMailId() {
        return mailMailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_mail_res_partner_rel.mail_mail_id
     *
     * @param mailMailId the value for mail_mail_res_partner_rel.mail_mail_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setMailMailId(Integer mailMailId) {
        this.mailMailId = mailMailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_mail_res_partner_rel.res_partner_id
     *
     * @return the value of mail_mail_res_partner_rel.res_partner_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getResPartnerId() {
        return resPartnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_mail_res_partner_rel.res_partner_id
     *
     * @param resPartnerId the value for mail_mail_res_partner_rel.res_partner_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setResPartnerId(Integer resPartnerId) {
        this.resPartnerId = resPartnerId;
    }
}