package com.altas.erp.eds.entity;

import java.util.Date;

public class MailWizardInviteEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_wizard_invite.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_wizard_invite.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_wizard_invite.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_wizard_invite.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_wizard_invite.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_wizard_invite.res_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer resId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_wizard_invite.send_mail
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean sendMail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_wizard_invite.id
     *
     * @return the value of mail_wizard_invite.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_wizard_invite.id
     *
     * @param id the value for mail_wizard_invite.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_wizard_invite.create_uid
     *
     * @return the value of mail_wizard_invite.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_wizard_invite.create_uid
     *
     * @param createUid the value for mail_wizard_invite.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_wizard_invite.write_uid
     *
     * @return the value of mail_wizard_invite.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_wizard_invite.write_uid
     *
     * @param writeUid the value for mail_wizard_invite.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_wizard_invite.write_date
     *
     * @return the value of mail_wizard_invite.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_wizard_invite.write_date
     *
     * @param writeDate the value for mail_wizard_invite.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_wizard_invite.create_date
     *
     * @return the value of mail_wizard_invite.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_wizard_invite.create_date
     *
     * @param createDate the value for mail_wizard_invite.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_wizard_invite.res_id
     *
     * @return the value of mail_wizard_invite.res_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_wizard_invite.res_id
     *
     * @param resId the value for mail_wizard_invite.res_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_wizard_invite.send_mail
     *
     * @return the value of mail_wizard_invite.send_mail
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getSendMail() {
        return sendMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_wizard_invite.send_mail
     *
     * @param sendMail the value for mail_wizard_invite.send_mail
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSendMail(Boolean sendMail) {
        this.sendMail = sendMail;
    }
}