package com.altas.erp.eds.entity;

public class MrpRoutingWorkcenterEntityWithBLOBs extends MrpRoutingWorkcenterEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_routing_workcenter.time_mode
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String timeMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_routing_workcenter.note
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_routing_workcenter.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_routing_workcenter.worksheet
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private byte[] worksheet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_routing_workcenter.batch
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String batch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_routing_workcenter.time_mode
     *
     * @return the value of mrp_routing_workcenter.time_mode
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getTimeMode() {
        return timeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_routing_workcenter.time_mode
     *
     * @param timeMode the value for mrp_routing_workcenter.time_mode
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setTimeMode(String timeMode) {
        this.timeMode = timeMode == null ? null : timeMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_routing_workcenter.note
     *
     * @return the value of mrp_routing_workcenter.note
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_routing_workcenter.note
     *
     * @param note the value for mrp_routing_workcenter.note
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_routing_workcenter.name
     *
     * @return the value of mrp_routing_workcenter.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_routing_workcenter.name
     *
     * @param name the value for mrp_routing_workcenter.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_routing_workcenter.worksheet
     *
     * @return the value of mrp_routing_workcenter.worksheet
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public byte[] getWorksheet() {
        return worksheet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_routing_workcenter.worksheet
     *
     * @param worksheet the value for mrp_routing_workcenter.worksheet
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWorksheet(byte[] worksheet) {
        this.worksheet = worksheet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_routing_workcenter.batch
     *
     * @return the value of mrp_routing_workcenter.batch
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_routing_workcenter.batch
     *
     * @param batch the value for mrp_routing_workcenter.batch
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }
}