package com.altas.erp.eds.entity;

import java.util.Date;

public class MrpWorkorderEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.next_work_order_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer nextWorkOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.duration
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.duration_expected
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double durationExpected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.date_finished
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date dateFinished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.capacity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.production_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date productionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.date_start
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date dateStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.message_last_post
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date messageLastPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.workcenter_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer workcenterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.duration_unit
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double durationUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.qty_produced
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double qtyProduced;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.qty_producing
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double qtyProducing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.date_planned_start
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date datePlannedStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.duration_percent
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer durationPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.date_planned_finished
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date datePlannedFinished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.production_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer productionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.operation_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer operationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrp_workorder.final_lot_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer finalLotId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.id
     *
     * @return the value of mrp_workorder.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.id
     *
     * @param id the value for mrp_workorder.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.write_uid
     *
     * @return the value of mrp_workorder.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.write_uid
     *
     * @param writeUid the value for mrp_workorder.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.next_work_order_id
     *
     * @return the value of mrp_workorder.next_work_order_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getNextWorkOrderId() {
        return nextWorkOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.next_work_order_id
     *
     * @param nextWorkOrderId the value for mrp_workorder.next_work_order_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setNextWorkOrderId(Integer nextWorkOrderId) {
        this.nextWorkOrderId = nextWorkOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.duration
     *
     * @return the value of mrp_workorder.duration
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.duration
     *
     * @param duration the value for mrp_workorder.duration
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDuration(Double duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.create_date
     *
     * @return the value of mrp_workorder.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.create_date
     *
     * @param createDate the value for mrp_workorder.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.duration_expected
     *
     * @return the value of mrp_workorder.duration_expected
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getDurationExpected() {
        return durationExpected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.duration_expected
     *
     * @param durationExpected the value for mrp_workorder.duration_expected
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDurationExpected(Double durationExpected) {
        this.durationExpected = durationExpected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.date_finished
     *
     * @return the value of mrp_workorder.date_finished
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getDateFinished() {
        return dateFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.date_finished
     *
     * @param dateFinished the value for mrp_workorder.date_finished
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDateFinished(Date dateFinished) {
        this.dateFinished = dateFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.create_uid
     *
     * @return the value of mrp_workorder.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.create_uid
     *
     * @param createUid the value for mrp_workorder.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.capacity
     *
     * @return the value of mrp_workorder.capacity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.capacity
     *
     * @param capacity the value for mrp_workorder.capacity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCapacity(Double capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.production_date
     *
     * @return the value of mrp_workorder.production_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getProductionDate() {
        return productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.production_date
     *
     * @param productionDate the value for mrp_workorder.production_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setProductionDate(Date productionDate) {
        this.productionDate = productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.date_start
     *
     * @return the value of mrp_workorder.date_start
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getDateStart() {
        return dateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.date_start
     *
     * @param dateStart the value for mrp_workorder.date_start
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.message_last_post
     *
     * @return the value of mrp_workorder.message_last_post
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getMessageLastPost() {
        return messageLastPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.message_last_post
     *
     * @param messageLastPost the value for mrp_workorder.message_last_post
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setMessageLastPost(Date messageLastPost) {
        this.messageLastPost = messageLastPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.workcenter_id
     *
     * @return the value of mrp_workorder.workcenter_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWorkcenterId() {
        return workcenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.workcenter_id
     *
     * @param workcenterId the value for mrp_workorder.workcenter_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWorkcenterId(Integer workcenterId) {
        this.workcenterId = workcenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.duration_unit
     *
     * @return the value of mrp_workorder.duration_unit
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getDurationUnit() {
        return durationUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.duration_unit
     *
     * @param durationUnit the value for mrp_workorder.duration_unit
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDurationUnit(Double durationUnit) {
        this.durationUnit = durationUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.qty_produced
     *
     * @return the value of mrp_workorder.qty_produced
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getQtyProduced() {
        return qtyProduced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.qty_produced
     *
     * @param qtyProduced the value for mrp_workorder.qty_produced
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setQtyProduced(Double qtyProduced) {
        this.qtyProduced = qtyProduced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.qty_producing
     *
     * @return the value of mrp_workorder.qty_producing
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getQtyProducing() {
        return qtyProducing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.qty_producing
     *
     * @param qtyProducing the value for mrp_workorder.qty_producing
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setQtyProducing(Double qtyProducing) {
        this.qtyProducing = qtyProducing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.write_date
     *
     * @return the value of mrp_workorder.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.write_date
     *
     * @param writeDate the value for mrp_workorder.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.date_planned_start
     *
     * @return the value of mrp_workorder.date_planned_start
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getDatePlannedStart() {
        return datePlannedStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.date_planned_start
     *
     * @param datePlannedStart the value for mrp_workorder.date_planned_start
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDatePlannedStart(Date datePlannedStart) {
        this.datePlannedStart = datePlannedStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.duration_percent
     *
     * @return the value of mrp_workorder.duration_percent
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getDurationPercent() {
        return durationPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.duration_percent
     *
     * @param durationPercent the value for mrp_workorder.duration_percent
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDurationPercent(Integer durationPercent) {
        this.durationPercent = durationPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.date_planned_finished
     *
     * @return the value of mrp_workorder.date_planned_finished
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getDatePlannedFinished() {
        return datePlannedFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.date_planned_finished
     *
     * @param datePlannedFinished the value for mrp_workorder.date_planned_finished
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDatePlannedFinished(Date datePlannedFinished) {
        this.datePlannedFinished = datePlannedFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.production_id
     *
     * @return the value of mrp_workorder.production_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getProductionId() {
        return productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.production_id
     *
     * @param productionId the value for mrp_workorder.production_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setProductionId(Integer productionId) {
        this.productionId = productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.operation_id
     *
     * @return the value of mrp_workorder.operation_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.operation_id
     *
     * @param operationId the value for mrp_workorder.operation_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setOperationId(Integer operationId) {
        this.operationId = operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrp_workorder.final_lot_id
     *
     * @return the value of mrp_workorder.final_lot_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getFinalLotId() {
        return finalLotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrp_workorder.final_lot_id
     *
     * @param finalLotId the value for mrp_workorder.final_lot_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setFinalLotId(Integer finalLotId) {
        this.finalLotId = finalLotId;
    }
}