package com.altas.erp.eds.entity;

import java.util.Date;

public class PaymentAcquirerEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.fees_active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean feesActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer journalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.registration_view_template_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer registrationViewTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.module_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.fees_dom_fixed
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double feesDomFixed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.fees_int_fixed
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double feesIntFixed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.website_published
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean websitePublished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.fees_int_var
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double feesIntVar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.fees_dom_var
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double feesDomVar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.view_template_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer viewTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_acquirer.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer sequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.id
     *
     * @return the value of payment_acquirer.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.id
     *
     * @param id the value for payment_acquirer.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.create_date
     *
     * @return the value of payment_acquirer.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.create_date
     *
     * @param createDate the value for payment_acquirer.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.write_date
     *
     * @return the value of payment_acquirer.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.write_date
     *
     * @param writeDate the value for payment_acquirer.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.fees_active
     *
     * @return the value of payment_acquirer.fees_active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getFeesActive() {
        return feesActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.fees_active
     *
     * @param feesActive the value for payment_acquirer.fees_active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setFeesActive(Boolean feesActive) {
        this.feesActive = feesActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.journal_id
     *
     * @return the value of payment_acquirer.journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getJournalId() {
        return journalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.journal_id
     *
     * @param journalId the value for payment_acquirer.journal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setJournalId(Integer journalId) {
        this.journalId = journalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.registration_view_template_id
     *
     * @return the value of payment_acquirer.registration_view_template_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getRegistrationViewTemplateId() {
        return registrationViewTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.registration_view_template_id
     *
     * @param registrationViewTemplateId the value for payment_acquirer.registration_view_template_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setRegistrationViewTemplateId(Integer registrationViewTemplateId) {
        this.registrationViewTemplateId = registrationViewTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.module_id
     *
     * @return the value of payment_acquirer.module_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.module_id
     *
     * @param moduleId the value for payment_acquirer.module_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.fees_dom_fixed
     *
     * @return the value of payment_acquirer.fees_dom_fixed
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getFeesDomFixed() {
        return feesDomFixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.fees_dom_fixed
     *
     * @param feesDomFixed the value for payment_acquirer.fees_dom_fixed
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setFeesDomFixed(Double feesDomFixed) {
        this.feesDomFixed = feesDomFixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.fees_int_fixed
     *
     * @return the value of payment_acquirer.fees_int_fixed
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getFeesIntFixed() {
        return feesIntFixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.fees_int_fixed
     *
     * @param feesIntFixed the value for payment_acquirer.fees_int_fixed
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setFeesIntFixed(Double feesIntFixed) {
        this.feesIntFixed = feesIntFixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.create_uid
     *
     * @return the value of payment_acquirer.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.create_uid
     *
     * @param createUid the value for payment_acquirer.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.company_id
     *
     * @return the value of payment_acquirer.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.company_id
     *
     * @param companyId the value for payment_acquirer.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.website_published
     *
     * @return the value of payment_acquirer.website_published
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getWebsitePublished() {
        return websitePublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.website_published
     *
     * @param websitePublished the value for payment_acquirer.website_published
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWebsitePublished(Boolean websitePublished) {
        this.websitePublished = websitePublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.fees_int_var
     *
     * @return the value of payment_acquirer.fees_int_var
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getFeesIntVar() {
        return feesIntVar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.fees_int_var
     *
     * @param feesIntVar the value for payment_acquirer.fees_int_var
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setFeesIntVar(Double feesIntVar) {
        this.feesIntVar = feesIntVar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.write_uid
     *
     * @return the value of payment_acquirer.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.write_uid
     *
     * @param writeUid the value for payment_acquirer.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.fees_dom_var
     *
     * @return the value of payment_acquirer.fees_dom_var
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getFeesDomVar() {
        return feesDomVar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.fees_dom_var
     *
     * @param feesDomVar the value for payment_acquirer.fees_dom_var
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setFeesDomVar(Double feesDomVar) {
        this.feesDomVar = feesDomVar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.view_template_id
     *
     * @return the value of payment_acquirer.view_template_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getViewTemplateId() {
        return viewTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.view_template_id
     *
     * @param viewTemplateId the value for payment_acquirer.view_template_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setViewTemplateId(Integer viewTemplateId) {
        this.viewTemplateId = viewTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_acquirer.sequence
     *
     * @return the value of payment_acquirer.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_acquirer.sequence
     *
     * @param sequence the value for payment_acquirer.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }
}