package com.altas.erp.eds.entity;

import java.util.Date;

public class PortalWizardEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_wizard.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_wizard.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_wizard.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_wizard.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_wizard.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_wizard.portal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer portalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_wizard.welcome_message
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String welcomeMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_wizard.id
     *
     * @return the value of portal_wizard.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_wizard.id
     *
     * @param id the value for portal_wizard.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_wizard.create_uid
     *
     * @return the value of portal_wizard.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_wizard.create_uid
     *
     * @param createUid the value for portal_wizard.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_wizard.write_uid
     *
     * @return the value of portal_wizard.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_wizard.write_uid
     *
     * @param writeUid the value for portal_wizard.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_wizard.write_date
     *
     * @return the value of portal_wizard.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_wizard.write_date
     *
     * @param writeDate the value for portal_wizard.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_wizard.create_date
     *
     * @return the value of portal_wizard.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_wizard.create_date
     *
     * @param createDate the value for portal_wizard.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_wizard.portal_id
     *
     * @return the value of portal_wizard.portal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getPortalId() {
        return portalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_wizard.portal_id
     *
     * @param portalId the value for portal_wizard.portal_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPortalId(Integer portalId) {
        this.portalId = portalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_wizard.welcome_message
     *
     * @return the value of portal_wizard.welcome_message
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getWelcomeMessage() {
        return welcomeMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_wizard.welcome_message
     *
     * @param welcomeMessage the value for portal_wizard.welcome_message
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWelcomeMessage(String welcomeMessage) {
        this.welcomeMessage = welcomeMessage == null ? null : welcomeMessage.trim();
    }
}