package com.altas.erp.eds.entity;

import java.util.Date;

public class ProductTemplateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.warranty
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double warranty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.list_price
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double listPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.weight
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.color
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.uom_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer uomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.sale_ok
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean saleOk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.purchase_ok
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean purchaseOk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.message_last_post
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date messageLastPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.uom_po_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer uomPoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.volume
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.categ_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer categId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.rental
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean rental;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.location_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.sale_delay
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double saleDelay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.warehouse_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer warehouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_template.produce_delay
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double produceDelay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.id
     *
     * @return the value of product_template.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.id
     *
     * @param id the value for product_template.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.warranty
     *
     * @return the value of product_template.warranty
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getWarranty() {
        return warranty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.warranty
     *
     * @param warranty the value for product_template.warranty
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWarranty(Double warranty) {
        this.warranty = warranty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.list_price
     *
     * @return the value of product_template.list_price
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getListPrice() {
        return listPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.list_price
     *
     * @param listPrice the value for product_template.list_price
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setListPrice(Double listPrice) {
        this.listPrice = listPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.weight
     *
     * @return the value of product_template.weight
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.weight
     *
     * @param weight the value for product_template.weight
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.sequence
     *
     * @return the value of product_template.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.sequence
     *
     * @param sequence the value for product_template.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.color
     *
     * @return the value of product_template.color
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.color
     *
     * @param color the value for product_template.color
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setColor(Integer color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.write_uid
     *
     * @return the value of product_template.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.write_uid
     *
     * @param writeUid the value for product_template.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.uom_id
     *
     * @return the value of product_template.uom_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getUomId() {
        return uomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.uom_id
     *
     * @param uomId the value for product_template.uom_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setUomId(Integer uomId) {
        this.uomId = uomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.create_date
     *
     * @return the value of product_template.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.create_date
     *
     * @param createDate the value for product_template.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.create_uid
     *
     * @return the value of product_template.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.create_uid
     *
     * @param createUid the value for product_template.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.sale_ok
     *
     * @return the value of product_template.sale_ok
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getSaleOk() {
        return saleOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.sale_ok
     *
     * @param saleOk the value for product_template.sale_ok
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSaleOk(Boolean saleOk) {
        this.saleOk = saleOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.purchase_ok
     *
     * @return the value of product_template.purchase_ok
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getPurchaseOk() {
        return purchaseOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.purchase_ok
     *
     * @param purchaseOk the value for product_template.purchase_ok
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPurchaseOk(Boolean purchaseOk) {
        this.purchaseOk = purchaseOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.message_last_post
     *
     * @return the value of product_template.message_last_post
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getMessageLastPost() {
        return messageLastPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.message_last_post
     *
     * @param messageLastPost the value for product_template.message_last_post
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setMessageLastPost(Date messageLastPost) {
        this.messageLastPost = messageLastPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.company_id
     *
     * @return the value of product_template.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.company_id
     *
     * @param companyId the value for product_template.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.uom_po_id
     *
     * @return the value of product_template.uom_po_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getUomPoId() {
        return uomPoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.uom_po_id
     *
     * @param uomPoId the value for product_template.uom_po_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setUomPoId(Integer uomPoId) {
        this.uomPoId = uomPoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.volume
     *
     * @return the value of product_template.volume
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.volume
     *
     * @param volume the value for product_template.volume
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.write_date
     *
     * @return the value of product_template.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.write_date
     *
     * @param writeDate the value for product_template.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.active
     *
     * @return the value of product_template.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.active
     *
     * @param active the value for product_template.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.categ_id
     *
     * @return the value of product_template.categ_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCategId() {
        return categId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.categ_id
     *
     * @param categId the value for product_template.categ_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCategId(Integer categId) {
        this.categId = categId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.rental
     *
     * @return the value of product_template.rental
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getRental() {
        return rental;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.rental
     *
     * @param rental the value for product_template.rental
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setRental(Boolean rental) {
        this.rental = rental;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.location_id
     *
     * @return the value of product_template.location_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.location_id
     *
     * @param locationId the value for product_template.location_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.sale_delay
     *
     * @return the value of product_template.sale_delay
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getSaleDelay() {
        return saleDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.sale_delay
     *
     * @param saleDelay the value for product_template.sale_delay
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSaleDelay(Double saleDelay) {
        this.saleDelay = saleDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.warehouse_id
     *
     * @return the value of product_template.warehouse_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.warehouse_id
     *
     * @param warehouseId the value for product_template.warehouse_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_template.produce_delay
     *
     * @return the value of product_template.produce_delay
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getProduceDelay() {
        return produceDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_template.produce_delay
     *
     * @param produceDelay the value for product_template.produce_delay
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setProduceDelay(Double produceDelay) {
        this.produceDelay = produceDelay;
    }
}