package com.altas.erp.eds.entity;

import java.util.Date;

public class ProductPricelistItemEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.fixed_price
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double fixedPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.price_discount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double priceDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.price_max_margin
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double priceMaxMargin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.date_end
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date dateEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer currencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.min_quantity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer minQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.percent_price
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double percentPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.date_start
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date dateStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.product_tmpl_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer productTmplId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.pricelist_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer pricelistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.price_surcharge
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double priceSurcharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.categ_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer categId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.product_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.price_round
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double priceRound;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.price_min_margin
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Double priceMinMargin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricelist_item.base_pricelist_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer basePricelistId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.id
     *
     * @return the value of product_pricelist_item.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.id
     *
     * @param id the value for product_pricelist_item.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.fixed_price
     *
     * @return the value of product_pricelist_item.fixed_price
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getFixedPrice() {
        return fixedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.fixed_price
     *
     * @param fixedPrice the value for product_pricelist_item.fixed_price
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setFixedPrice(Double fixedPrice) {
        this.fixedPrice = fixedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.create_date
     *
     * @return the value of product_pricelist_item.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.create_date
     *
     * @param createDate the value for product_pricelist_item.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.price_discount
     *
     * @return the value of product_pricelist_item.price_discount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getPriceDiscount() {
        return priceDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.price_discount
     *
     * @param priceDiscount the value for product_pricelist_item.price_discount
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPriceDiscount(Double priceDiscount) {
        this.priceDiscount = priceDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.sequence
     *
     * @return the value of product_pricelist_item.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.sequence
     *
     * @param sequence the value for product_pricelist_item.sequence
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.price_max_margin
     *
     * @return the value of product_pricelist_item.price_max_margin
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getPriceMaxMargin() {
        return priceMaxMargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.price_max_margin
     *
     * @param priceMaxMargin the value for product_pricelist_item.price_max_margin
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPriceMaxMargin(Double priceMaxMargin) {
        this.priceMaxMargin = priceMaxMargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.date_end
     *
     * @return the value of product_pricelist_item.date_end
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getDateEnd() {
        return dateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.date_end
     *
     * @param dateEnd the value for product_pricelist_item.date_end
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.write_uid
     *
     * @return the value of product_pricelist_item.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.write_uid
     *
     * @param writeUid the value for product_pricelist_item.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.currency_id
     *
     * @return the value of product_pricelist_item.currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCurrencyId() {
        return currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.currency_id
     *
     * @param currencyId the value for product_pricelist_item.currency_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.min_quantity
     *
     * @return the value of product_pricelist_item.min_quantity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getMinQuantity() {
        return minQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.min_quantity
     *
     * @param minQuantity the value for product_pricelist_item.min_quantity
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setMinQuantity(Integer minQuantity) {
        this.minQuantity = minQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.create_uid
     *
     * @return the value of product_pricelist_item.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.create_uid
     *
     * @param createUid the value for product_pricelist_item.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.percent_price
     *
     * @return the value of product_pricelist_item.percent_price
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getPercentPrice() {
        return percentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.percent_price
     *
     * @param percentPrice the value for product_pricelist_item.percent_price
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPercentPrice(Double percentPrice) {
        this.percentPrice = percentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.date_start
     *
     * @return the value of product_pricelist_item.date_start
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getDateStart() {
        return dateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.date_start
     *
     * @param dateStart the value for product_pricelist_item.date_start
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.company_id
     *
     * @return the value of product_pricelist_item.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.company_id
     *
     * @param companyId the value for product_pricelist_item.company_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.product_tmpl_id
     *
     * @return the value of product_pricelist_item.product_tmpl_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getProductTmplId() {
        return productTmplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.product_tmpl_id
     *
     * @param productTmplId the value for product_pricelist_item.product_tmpl_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setProductTmplId(Integer productTmplId) {
        this.productTmplId = productTmplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.pricelist_id
     *
     * @return the value of product_pricelist_item.pricelist_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getPricelistId() {
        return pricelistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.pricelist_id
     *
     * @param pricelistId the value for product_pricelist_item.pricelist_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPricelistId(Integer pricelistId) {
        this.pricelistId = pricelistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.price_surcharge
     *
     * @return the value of product_pricelist_item.price_surcharge
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getPriceSurcharge() {
        return priceSurcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.price_surcharge
     *
     * @param priceSurcharge the value for product_pricelist_item.price_surcharge
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPriceSurcharge(Double priceSurcharge) {
        this.priceSurcharge = priceSurcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.write_date
     *
     * @return the value of product_pricelist_item.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.write_date
     *
     * @param writeDate the value for product_pricelist_item.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.categ_id
     *
     * @return the value of product_pricelist_item.categ_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCategId() {
        return categId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.categ_id
     *
     * @param categId the value for product_pricelist_item.categ_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCategId(Integer categId) {
        this.categId = categId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.product_id
     *
     * @return the value of product_pricelist_item.product_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.product_id
     *
     * @param productId the value for product_pricelist_item.product_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.price_round
     *
     * @return the value of product_pricelist_item.price_round
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getPriceRound() {
        return priceRound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.price_round
     *
     * @param priceRound the value for product_pricelist_item.price_round
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPriceRound(Double priceRound) {
        this.priceRound = priceRound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.price_min_margin
     *
     * @return the value of product_pricelist_item.price_min_margin
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Double getPriceMinMargin() {
        return priceMinMargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.price_min_margin
     *
     * @param priceMinMargin the value for product_pricelist_item.price_min_margin
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPriceMinMargin(Double priceMinMargin) {
        this.priceMinMargin = priceMinMargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricelist_item.base_pricelist_id
     *
     * @return the value of product_pricelist_item.base_pricelist_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getBasePricelistId() {
        return basePricelistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricelist_item.base_pricelist_id
     *
     * @param basePricelistId the value for product_pricelist_item.base_pricelist_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setBasePricelistId(Integer basePricelistId) {
        this.basePricelistId = basePricelistId;
    }
}