package com.altas.erp.eds.entity;

import java.util.Date;

public class ResBankEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_bank.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_bank.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_bank.country
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_bank.state
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_bank.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_bank.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_bank.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_bank.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_bank.id
     *
     * @return the value of res_bank.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_bank.id
     *
     * @param id the value for res_bank.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_bank.create_uid
     *
     * @return the value of res_bank.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_bank.create_uid
     *
     * @param createUid the value for res_bank.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_bank.country
     *
     * @return the value of res_bank.country
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_bank.country
     *
     * @param country the value for res_bank.country
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCountry(Integer country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_bank.state
     *
     * @return the value of res_bank.state
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_bank.state
     *
     * @param state the value for res_bank.state
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_bank.write_date
     *
     * @return the value of res_bank.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_bank.write_date
     *
     * @param writeDate the value for res_bank.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_bank.active
     *
     * @return the value of res_bank.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_bank.active
     *
     * @param active the value for res_bank.active
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_bank.create_date
     *
     * @return the value of res_bank.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_bank.create_date
     *
     * @param createDate the value for res_bank.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_bank.write_uid
     *
     * @return the value of res_bank.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_bank.write_uid
     *
     * @param writeUid the value for res_bank.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }
}