package com.altas.erp.eds.entity;

public class StockLocationPathEntityWithBLOBs extends StockLocationPathEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_location_path.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_location_path.auto
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String auto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_location_path.name
     *
     * @return the value of stock_location_path.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_location_path.name
     *
     * @param name the value for stock_location_path.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_location_path.auto
     *
     * @return the value of stock_location_path.auto
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getAuto() {
        return auto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_location_path.auto
     *
     * @param auto the value for stock_location_path.auto
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setAuto(String auto) {
        this.auto = auto == null ? null : auto.trim();
    }
}