package com.altas.erp.eds.entity;

public class StockWarehouseEntityWithBLOBs extends StockWarehouseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_warehouse.reception_steps
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String receptionSteps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_warehouse.delivery_steps
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String deliverySteps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_warehouse.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_warehouse.reception_steps
     *
     * @return the value of stock_warehouse.reception_steps
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getReceptionSteps() {
        return receptionSteps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_warehouse.reception_steps
     *
     * @param receptionSteps the value for stock_warehouse.reception_steps
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setReceptionSteps(String receptionSteps) {
        this.receptionSteps = receptionSteps == null ? null : receptionSteps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_warehouse.delivery_steps
     *
     * @return the value of stock_warehouse.delivery_steps
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getDeliverySteps() {
        return deliverySteps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_warehouse.delivery_steps
     *
     * @param deliverySteps the value for stock_warehouse.delivery_steps
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setDeliverySteps(String deliverySteps) {
        this.deliverySteps = deliverySteps == null ? null : deliverySteps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_warehouse.name
     *
     * @return the value of stock_warehouse.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_warehouse.name
     *
     * @param name the value for stock_warehouse.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}