package com.altas.erp.eds.entity;

import java.util.Date;

public class StockBackorderConfirmationEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_backorder_confirmation.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_backorder_confirmation.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_backorder_confirmation.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer writeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_backorder_confirmation.pick_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Integer pickId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_backorder_confirmation.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_backorder_confirmation.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_backorder_confirmation.id
     *
     * @return the value of stock_backorder_confirmation.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_backorder_confirmation.id
     *
     * @param id the value for stock_backorder_confirmation.id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_backorder_confirmation.create_uid
     *
     * @return the value of stock_backorder_confirmation.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_backorder_confirmation.create_uid
     *
     * @param createUid the value for stock_backorder_confirmation.create_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_backorder_confirmation.write_uid
     *
     * @return the value of stock_backorder_confirmation.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getWriteUid() {
        return writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_backorder_confirmation.write_uid
     *
     * @param writeUid the value for stock_backorder_confirmation.write_uid
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_backorder_confirmation.pick_id
     *
     * @return the value of stock_backorder_confirmation.pick_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Integer getPickId() {
        return pickId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_backorder_confirmation.pick_id
     *
     * @param pickId the value for stock_backorder_confirmation.pick_id
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPickId(Integer pickId) {
        this.pickId = pickId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_backorder_confirmation.write_date
     *
     * @return the value of stock_backorder_confirmation.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_backorder_confirmation.write_date
     *
     * @param writeDate the value for stock_backorder_confirmation.write_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_backorder_confirmation.create_date
     *
     * @return the value of stock_backorder_confirmation.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_backorder_confirmation.create_date
     *
     * @param createDate the value for stock_backorder_confirmation.create_date
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}