package com.altas.erp.eds.entity;

public class StockProductionLotEntityWithBLOBs extends StockProductionLotEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_production_lot.ref
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String ref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_production_lot.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_production_lot.ref
     *
     * @return the value of stock_production_lot.ref
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_production_lot.ref
     *
     * @param ref the value for stock_production_lot.ref
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setRef(String ref) {
        this.ref = ref == null ? null : ref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_production_lot.name
     *
     * @return the value of stock_production_lot.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_production_lot.name
     *
     * @param name the value for stock_production_lot.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}