package com.altas.erp.eds.entity;

public class WebPlannerEntityWithBLOBs extends WebPlannerEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_planner.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_planner.planner_application
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String plannerApplication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_planner.tooltip_planner
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    private String tooltipPlanner;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_planner.name
     *
     * @return the value of web_planner.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_planner.name
     *
     * @param name the value for web_planner.name
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_planner.planner_application
     *
     * @return the value of web_planner.planner_application
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getPlannerApplication() {
        return plannerApplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_planner.planner_application
     *
     * @param plannerApplication the value for web_planner.planner_application
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setPlannerApplication(String plannerApplication) {
        this.plannerApplication = plannerApplication == null ? null : plannerApplication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_planner.tooltip_planner
     *
     * @return the value of web_planner.tooltip_planner
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public String getTooltipPlanner() {
        return tooltipPlanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_planner.tooltip_planner
     *
     * @param tooltipPlanner the value for web_planner.tooltip_planner
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    public void setTooltipPlanner(String tooltipPlanner) {
        this.tooltipPlanner = tooltipPlanner == null ? null : tooltipPlanner.trim();
    }
}