package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.AccountAgedTrialBalanceAccountJournalRelEntity;

public interface AccountAgedTrialBalanceAccountJournalRelEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_aged_trial_balance_account_journal_rel
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(AccountAgedTrialBalanceAccountJournalRelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_aged_trial_balance_account_journal_rel
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(AccountAgedTrialBalanceAccountJournalRelEntity record);
}