package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.AccountReconcileModelEntity;
import com.altas.erp.eds.entity.AccountReconcileModelEntityWithBLOBs;

public interface AccountReconcileModelEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_reconcile_model
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_reconcile_model
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(AccountReconcileModelEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_reconcile_model
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(AccountReconcileModelEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_reconcile_model
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    AccountReconcileModelEntityWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_reconcile_model
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(AccountReconcileModelEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_reconcile_model
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AccountReconcileModelEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_reconcile_model
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(AccountReconcileModelEntity record);
}