package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.AccountAccountFinancialReportEntity;

public interface AccountAccountFinancialReportEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_account_financial_report
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(AccountAccountFinancialReportEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_account_financial_report
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(AccountAccountFinancialReportEntity record);
}