package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.AccountReportPartnerLedgerEntity;
import com.altas.erp.eds.entity.AccountReportPartnerLedgerEntityWithBLOBs;

public interface AccountReportPartnerLedgerEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_report_partner_ledger
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_report_partner_ledger
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(AccountReportPartnerLedgerEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_report_partner_ledger
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(AccountReportPartnerLedgerEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_report_partner_ledger
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    AccountReportPartnerLedgerEntityWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_report_partner_ledger
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(AccountReportPartnerLedgerEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_report_partner_ledger
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AccountReportPartnerLedgerEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_report_partner_ledger
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(AccountReportPartnerLedgerEntity record);
}