package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.AccountReportGeneralLedgerJournalRelEntity;

public interface AccountReportGeneralLedgerJournalRelEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_report_general_ledger_journal_rel
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(AccountReportGeneralLedgerJournalRelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_report_general_ledger_journal_rel
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(AccountReportGeneralLedgerJournalRelEntity record);
}