package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.AccountInvoiceRefundEntity;
import com.altas.erp.eds.entity.AccountInvoiceRefundEntityWithBLOBs;

public interface AccountInvoiceRefundEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_invoice_refund
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_invoice_refund
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(AccountInvoiceRefundEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_invoice_refund
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(AccountInvoiceRefundEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_invoice_refund
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    AccountInvoiceRefundEntityWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_invoice_refund
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(AccountInvoiceRefundEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_invoice_refund
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AccountInvoiceRefundEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_invoice_refund
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(AccountInvoiceRefundEntity record);
}