package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.AccountFiscalPositionTaxEntity;

public interface AccountFiscalPositionTaxEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_fiscal_position_tax
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_fiscal_position_tax
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(AccountFiscalPositionTaxEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_fiscal_position_tax
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(AccountFiscalPositionTaxEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_fiscal_position_tax
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    AccountFiscalPositionTaxEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_fiscal_position_tax
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(AccountFiscalPositionTaxEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_fiscal_position_tax
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(AccountFiscalPositionTaxEntity record);
}