package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.AccountAccountTemplateTaxRelEntity;

public interface AccountAccountTemplateTaxRelEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_account_template_tax_rel
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(AccountAccountTemplateTaxRelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_account_template_tax_rel
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(AccountAccountTemplateTaxRelEntity record);
}