package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.AccountMoveReversalEntity;

public interface AccountMoveReversalEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_move_reversal
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_move_reversal
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(AccountMoveReversalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_move_reversal
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(AccountMoveReversalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_move_reversal
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    AccountMoveReversalEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_move_reversal
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(AccountMoveReversalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_move_reversal
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(AccountMoveReversalEntity record);
}