package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.BaseModuleUpdateEntity;

public interface BaseModuleUpdateEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_module_update
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_module_update
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(BaseModuleUpdateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_module_update
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(BaseModuleUpdateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_module_update
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    BaseModuleUpdateEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_module_update
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(BaseModuleUpdateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_module_update
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(BaseModuleUpdateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_module_update
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(BaseModuleUpdateEntity record);
}