package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.EmailTemplatePreviewEntity;
import com.altas.erp.eds.entity.EmailTemplatePreviewEntityWithBLOBs;

public interface EmailTemplatePreviewEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_template_preview
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_template_preview
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(EmailTemplatePreviewEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_template_preview
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(EmailTemplatePreviewEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_template_preview
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    EmailTemplatePreviewEntityWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_template_preview
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(EmailTemplatePreviewEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_template_preview
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(EmailTemplatePreviewEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_template_preview
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(EmailTemplatePreviewEntity record);
}