package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.IrActReportXmlEntity;
import com.altas.erp.eds.entity.IrActReportXmlEntityWithBLOBs;

public interface IrActReportXmlEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_act_report_xml
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_act_report_xml
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(IrActReportXmlEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_act_report_xml
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(IrActReportXmlEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_act_report_xml
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    IrActReportXmlEntityWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_act_report_xml
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(IrActReportXmlEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_act_report_xml
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(IrActReportXmlEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_act_report_xml
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(IrActReportXmlEntity record);
}