package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.IrModelAccessEntity;

public interface IrModelAccessEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_model_access
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_model_access
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(IrModelAccessEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_model_access
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(IrModelAccessEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_model_access
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    IrModelAccessEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_model_access
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(IrModelAccessEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_model_access
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(IrModelAccessEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ir_model_access
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(IrModelAccessEntity record);
}