package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.MakeProcurementStockLocationRouteRelEntity;

public interface MakeProcurementStockLocationRouteRelEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_procurement_stock_location_route_rel
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(MakeProcurementStockLocationRouteRelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_procurement_stock_location_route_rel
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(MakeProcurementStockLocationRouteRelEntity record);
}