package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.MrpWorkcenterProductivityLossEntity;
import com.altas.erp.eds.entity.MrpWorkcenterProductivityLossEntityWithBLOBs;

public interface MrpWorkcenterProductivityLossEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mrp_workcenter_productivity_loss
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mrp_workcenter_productivity_loss
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(MrpWorkcenterProductivityLossEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mrp_workcenter_productivity_loss
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(MrpWorkcenterProductivityLossEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mrp_workcenter_productivity_loss
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    MrpWorkcenterProductivityLossEntityWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mrp_workcenter_productivity_loss
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(MrpWorkcenterProductivityLossEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mrp_workcenter_productivity_loss
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(MrpWorkcenterProductivityLossEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mrp_workcenter_productivity_loss
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(MrpWorkcenterProductivityLossEntity record);
}