package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.ResUsersEntity;
import com.altas.erp.eds.entity.ResUsersEntityWithBLOBs;

public interface ResUsersEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_users
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_users
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(ResUsersEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_users
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(ResUsersEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_users
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    ResUsersEntityWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_users
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(ResUsersEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_users
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ResUsersEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_users
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(ResUsersEntity record);
}