package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.StockPackOperationLotEntity;

public interface StockPackOperationLotEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_pack_operation_lot
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_pack_operation_lot
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(StockPackOperationLotEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_pack_operation_lot
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(StockPackOperationLotEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_pack_operation_lot
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    StockPackOperationLotEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_pack_operation_lot
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(StockPackOperationLotEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_pack_operation_lot
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(StockPackOperationLotEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_pack_operation_lot
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(StockPackOperationLotEntity record);
}