package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.StockMoveOperationLinkEntity;

public interface StockMoveOperationLinkEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_move_operation_link
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_move_operation_link
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(StockMoveOperationLinkEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_move_operation_link
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(StockMoveOperationLinkEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_move_operation_link
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    StockMoveOperationLinkEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_move_operation_link
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(StockMoveOperationLinkEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_move_operation_link
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(StockMoveOperationLinkEntity record);
}