package com.altas.erp.eds.dao;

import com.altas.erp.eds.entity.StockQuantEntity;

public interface StockQuantEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quant
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quant
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insert(StockQuantEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quant
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int insertSelective(StockQuantEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quant
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    StockQuantEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quant
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(StockQuantEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quant
     *
     * @mbg.generated Thu Apr 05 20:29:43 CST 2018
     */
    int updateByPrimaryKey(StockQuantEntity record);
}